import { User, MessageSquare, Download, Share2, MoreHorizontal, ArrowLeft, Clock, Users, Calendar, AlertTriangle, CheckCircle, Ticket } from 'lucide-react';
import { motion } from 'framer-motion';
import { cn } from '../lib/utils';

interface TranscriptSegment {
    speaker: string;
    text: string;
    start: number;
    end: number;
}

interface AnalysisData {
    conflicts?: { text: string; speaker: string }[];
    resolutions?: { text: string; speaker: string }[];
    events?: { subject: string; date: string; time: string }[];
}

interface TranscriptViewProps {
    transcript: TranscriptSegment[];
    onBack: () => void;
    speakerMap: Record<string, string>;
    analysis: AnalysisData | null;
}

export function TranscriptView({ transcript, onBack, speakerMap, analysis }: TranscriptViewProps) {
    const formatTime = (seconds: number) => {
        const mins = Math.floor(seconds / 60);
        const secs = Math.floor(seconds % 60);
        return `${mins}:${secs.toString().padStart(2, '0')}`;
    };

    const totalSpeakers = new Set(transcript.map(t => t.speaker)).size;
    const lastTimestamp = transcript[transcript.length - 1]?.end || 0;

    const handleExport = () => {
        const textContent = transcript.map(segment => {
            const speakerName = speakerMap[segment.speaker] || segment.speaker;
            return `[${formatTime(segment.start)}] ${speakerName}: ${segment.text}`;
        }).join('\n\n');

        const blob = new Blob([textContent], { type: 'text/plain' });
        const url = URL.createObjectURL(blob);
        const link = document.createElement('a');
        link.href = url;
        link.download = `transcript-${new Date().toISOString().split('T')[0]}.txt`;
        document.body.appendChild(link);
        link.click();
        document.body.removeChild(link);
        URL.revokeObjectURL(url);
    };

    const addToCalendar = (event: { subject: string; date: string; time: string }) => {
        // Create a basic .ics content
        const icsContent = `BEGIN:VCALENDAR
VERSION:2.0
BEGIN:VEVENT
SUMMARY:${event.subject}
DTSTART:${event.date.replace(/-/g, '')}T${event.time.replace(/:/g, '')}00
DESCRIPTION:Generated by Antigravity AI
END:VEVENT
END:VCALENDAR`;

        const blob = new Blob([icsContent], { type: 'text/calendar' });
        const url = URL.createObjectURL(blob);
        const link = document.createElement('a');
        link.href = url;
        link.download = `event-${event.subject.replace(/\s+/g, '-')}.ics`;
        document.body.appendChild(link);
        link.click();
        document.body.removeChild(link);
    };

    // Helper to check if text contains conflict or resolution
    const getSentimentStyle = (text: string) => {
        const isConflict = analysis?.conflicts?.some(c => text.includes(c.text));
        const isResolution = analysis?.resolutions?.some(r => text.includes(r.text));

        if (isConflict) return "border-red-500/50 bg-red-500/10 shadow-[0_0_15px_rgba(239,68,68,0.2)]";
        if (isResolution) return "border-green-500/50 bg-green-500/10 shadow-[0_0_15px_rgba(34,197,94,0.2)]";
        return "";
    };

    return (
        <div className="h-full flex space-x-6 max-w-7xl mx-auto w-full px-4">
            <div className="flex-1 flex flex-col space-y-6">
                {/* Header */}
                <div className="flex items-center justify-between shrink-0">
                    <div className="flex items-center space-x-4">
                        <button
                            onClick={onBack}
                            className="p-2 hover:bg-slate-800 rounded-xl transition-colors text-slate-400 hover:text-white"
                        >
                            <ArrowLeft className="w-5 h-5" />
                        </button>
                        <div>
                            <h2 className="text-2xl font-bold text-white">Meeting Transcript</h2>
                            <div className="flex items-center space-x-4 text-sm text-slate-400 mt-1">
                                <span className="flex items-center space-x-1">
                                    <Clock className="w-4 h-4" />
                                    <span>{formatTime(lastTimestamp)}</span>
                                </span>
                                <span className="flex items-center space-x-1">
                                    <Users className="w-4 h-4" />
                                    <span>{totalSpeakers} Speakers detected</span>
                                </span>
                            </div>
                        </div>
                    </div>

                    <div className="flex items-center space-x-3">
                        <button
                            onClick={handleExport}
                            className="flex items-center space-x-2 px-4 py-2 bg-slate-800 hover:bg-slate-700 text-slate-200 rounded-xl transition-all font-medium border border-slate-700"
                        >
                            <Download className="w-4 h-4" />
                            <span>Export</span>
                        </button>
                    </div>
                </div>

                {/* Transcript List */}
                <div className="flex-1 overflow-y-auto pr-4 space-y-8 scrollbar-hide py-4">
                    {transcript.map((segment, i) => {
                        const isUser = i % 2 === 0;
                        const displayName = speakerMap[segment.speaker] || segment.speaker;
                        const sentimentClass = getSentimentStyle(segment.text);

                        return (
                            <motion.div
                                initial={{ opacity: 0, x: isUser ? -10 : 10 }}
                                animate={{ opacity: 1, x: 0 }}
                                transition={{ delay: i * 0.05 }}
                                key={i}
                                className={cn(
                                    "flex flex-col space-y-2",
                                    !isUser && "items-end text-right"
                                )}
                            >
                                <div className={cn(
                                    "flex items-center space-x-3",
                                    !isUser && "flex-row-reverse space-x-reverse"
                                )}>
                                    <div className={cn(
                                        "w-8 h-8 rounded-full flex items-center justify-center text-xs font-bold ring-2 ring-slate-800",
                                        isUser ? "bg-indigo-600 text-white" : "bg-emerald-600 text-white"
                                    )}>
                                        <User className="w-4 h-4" />
                                    </div>
                                    <div className="flex items-center space-x-2">
                                        <span className="text-sm font-bold text-slate-100">{displayName}</span>
                                        <span className="text-[10px] font-mono text-slate-500 bg-slate-800 px-1.5 py-0.5 rounded leading-tight">
                                            {formatTime(segment.start)}
                                        </span>
                                    </div>
                                </div>

                                <div className={cn(
                                    "group relative max-w-[80%]",
                                    !isUser && "text-right"
                                )}>
                                    <div className={cn(
                                        "p-5 rounded-[2rem] text-[15px] leading-relaxed relative transition-all duration-300",
                                        isUser
                                            ? "bg-slate-800/80 backdrop-blur-md border border-slate-700/50 text-slate-200 rounded-tl-none hover:bg-slate-800"
                                            : "bg-indigo-600 border border-indigo-500 text-white rounded-tr-none shadow-xl shadow-indigo-900/10 hover:bg-indigo-500",
                                        sentimentClass
                                    )}>
                                        {segment.text}

                                        {sentimentClass.includes('red') && (
                                            <div className="absolute -top-3 -right-3 bg-red-500 text-white p-1 rounded-full shadow-lg" title="Conflict Detected">
                                                <AlertTriangle className="w-3 h-3" />
                                            </div>
                                        )}
                                        {sentimentClass.includes('green') && (
                                            <div className="absolute -top-3 -right-3 bg-green-500 text-white p-1 rounded-full shadow-lg" title="Resolution Reached">
                                                <CheckCircle className="w-3 h-3" />
                                            </div>
                                        )}
                                    </div>
                                </div>
                            </motion.div>
                        );
                    })}
                </div>
            </div>

            {/* AI Insights Panel (Right Side) */}
            {analysis && (
                <div className="w-80 shrink-0 border-l border-slate-800 pl-6 py-6 overflow-y-auto space-y-6">
                    <h3 className="text-lg font-bold text-white flex items-center space-x-2">
                        <Ticket className="w-5 h-5 text-indigo-400" />
                        <span>AI Insights</span>
                    </h3>

                    {/* Detected Events */}
                    {analysis.events && analysis.events.length > 0 && (
                        <div className="space-y-4">
                            <h4 className="text-xs font-bold text-slate-500 uppercase tracking-wider">Detected Events</h4>
                            {analysis.events.map((event, i) => (
                                <div key={i} className="p-4 bg-slate-900/50 border border-slate-800 rounded-xl space-y-3 hover:border-indigo-500/30 transition-colors">
                                    <div className="flex items-start justify-between">
                                        <div>
                                            <p className="font-bold text-white text-sm">{event.subject}</p>
                                            <p className="text-xs text-slate-400 mt-1 flex items-center">
                                                <Calendar className="w-3 h-3 mr-1" />
                                                {event.date} at {event.time}
                                            </p>
                                        </div>
                                    </div>
                                    <button
                                        onClick={() => addToCalendar(event)}
                                        className="w-full py-2 bg-indigo-600/10 hover:bg-indigo-600/20 text-indigo-400 text-xs font-bold rounded-lg transition-colors border border-indigo-500/20"
                                    >
                                        Add to Calendar (.ics)
                                    </button>
                                </div>
                            ))}
                        </div>
                    )}

                    {/* Summary Stats */}
                    <div className="space-y-4">
                        <h4 className="text-xs font-bold text-slate-500 uppercase tracking-wider">Conversation Stats</h4>
                        <div className="grid grid-cols-2 gap-3">
                            <div className="p-3 bg-red-500/10 border border-red-500/20 rounded-xl text-center">
                                <p className="text-2xl font-bold text-red-500">{analysis.conflicts?.length || 0}</p>
                                <p className="text-[10px] text-red-400 uppercase font-bold">Conflicts</p>
                            </div>
                            <div className="p-3 bg-green-500/10 border border-green-500/20 rounded-xl text-center">
                                <p className="text-2xl font-bold text-green-500">{analysis.resolutions?.length || 0}</p>
                                <p className="text-[10px] text-green-400 uppercase font-bold">Resolved</p>
                            </div>
                        </div>
                    </div>
                </div>
            )}
        </div>
    );
}
